#!/bin/bash
bashdir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. $bashdir/config.cfg

if [ -d $bashdir/sender ]; then
    echo -e "Found sender. Skipping download"
else
    wget -t 5 -O Zapretyan.tar 'https://github.com/SHULKERPLAY/Zapretyan/releases/download/1.1/zapretyan.tar' && tar -xf Zapretyan.tar && rm Zapretyan.tar
fi

echo -e "Found $bashdir"
echo Script uses relative paths - Checking files
if [ -e $bashdir/sender/send.js ]; then
    echo Found JS sender
    if [ -e $bashdir/shell/discordrkn.sh ]; then
        echo Found shell files
    else
        echo -e "ERROR. CANNOT FIND $bashdir/shell/discordrkn.sh . Aborting..."
        exit 1
    fi
else
    echo -e "ERROR. CANNOT FIND $bashdir/sender/send.js . Aborting..."
    exit 1
fi
echo Check complete
sleep 2
clear

echo Enter absolute path where zapretyan will be and we prepare all for you
echo If you want to change path to dir in the future, you will need to change them in config.cfg
echo e.g. /root/zapretyan
read -r installpath

mkdir $installpath
if [ -d $installpath ]; then
    echo -e "Directory Created ($installpath)"
else
    echo -e "ERROR. CANNOT FIND $installpath . Do i have access to directory or my path is wrong?"
    exit 1
fi
sleep 2
clear

#curl -o- https://fnm.vercel.app/install | bash && source /root/.bashrc && fnm install 24
while true; do
    echo Zapretyan requires nodejs, npm, git, wget
    read -r -p "Do you want to install dependencies? (Up to 430 MB of additional disk space can be used) Y/N" yn
    case $yn in
        [Yy]* ) apt update && apt install npm nodejs git wget -y; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
sleep 2
clear

echo If you change the method of parsing bans from antifilter to github, you will need additional binary to unpack .dat routing files
echo You need wget to download this
while true; do
    read -r -p "Do you want to download v2dat decompiler? (Optional)(9.6 MB) Y/N" yn
    case $yn in
        [Yy]* ) wget -t 5 -O shell/v2dat 'https://github.com/SHULKERPLAY/Zapretyan/raw/refs/heads/main/bin/v2dat'; break;;
        [Nn]* ) break;;
        * ) echo "Please answer yes or no.";;
    esac
done
sleep 2
clear

echo Installing Zapretyan in 10 seconds...
sleep 10
    if [ -e $bashdir/sender/node_modules/.package-lock.json ]; then
        echo Found node modules. Skipping...
    else
        echo Downloading node modules...
		wget -t 5 -O sender/node.tar 'https://www.dropbox.com/scl/fi/6ug26cl0h5bx8vfrgr2kf/node_modules.tar?rlkey=dpr2vqn2hbeqrzm0d20ikxjf7&e=2&st=llm6v7x8&dl=1'
		tar -xf sender/node.tar -C sender
		rm sender/node.tar
    fi

echo Moving shell to install path...
mv shell $installpath
echo Moving sender to install path...
mv sender $installpath
echo Changing dir to install path...
cd $installpath

echo recheck files
if [ -e $installpath/sender/send.js ]; then
    echo Found JS sender
    if [ -e $installpath/shell/discordrkn.sh ]; then
        echo Found shell files
    else
        echo -e "ERROR. CANNOT FIND $installpath/shell/discordrkn.sh . Aborting..."
        exit 1
    fi
else
    echo -e "ERROR. CANNOT FIND $installpath/sender/send.js . Aborting..."
    exit 1
fi

echo Modifying config.cfg...
echo -e "#AUTOCONFIG. REMOVE LINES BELOW TO EDIT SAME VARIABLES ABOVE" >> shell/config.cfg
echo -e "shdir=$installpath/shell" >> shell/config.cfg
echo -e "jsdir=$installpath/sender" >> shell/config.cfg

echo Building service
echo -e "#AUTOGENERATED BY INSTALLER" > zapretyan.service
echo -e "[Unit]\nDescription=Zapretyan - Russia internet bans notifier. https://github.com/SHULKERPLAY/Zapretyan/\n" >> zapretyan.service
echo -e "[Service]\nExecStart=/bin/bash $installpath/shell/discordrkn.sh\n" >> zapretyan.service

echo Building timer
echo -e "#AUTOGENERATED BY INSTALLER" > zapretyan.timer
echo -e "[Unit]\nDescription=Trigger for Zapretyan - Russia internet bans notifier\n" >> zapretyan.timer
echo -e "[Timer]\nPersistent=true\nOnCalendar=Mon..Sun *-*-* 08:00:00\n" >> zapretyan.timer
echo -e "[Install]\nWantedBy=timers.target" >> zapretyan.timer

echo Installing timer
mv zapretyan.service /etc/systemd/system
mv zapretyan.timer /etc/systemd/system
echo Enabling timer
systemctl enable zapretyan.timer
systemctl start zapretyan.timer

echo -e "\n\n\nDone!\nEdit /etc/systemd/system/zapretyan.timer if you want to change time when checks are starting (Default: 8 AM).\nType 'systemctl status zapretyan.timer' to check if installation complete.\nsystemctl disable zapretyan.timer to stop service."
echo -e "Now you need to edit $installpath/shell/config.cfg to enable notifications and setup your Discord channels ID"
echo -e "AND INSERT YOUR BOT TOKEN IN $installpath/sender/config.json"